- name: Compute Engine Instance
  hosts: localhost
  vars:
    service_account_email: "adriancc5.5@gmail.com"
    credentials_file: "/home/adrian/.ssh/google_compute_engine"
    project_id: "everisconf"
  tasks:
    - name: create multiple instances
      gce:
        instance_names: test1
        zone: us-east1-b
        machine_type: n1-standard-1
        image: ubuntu-1804-bionic-v20180823
        state: present
        service_account_email: "{{ service_account_email }}"
        credentials_file: "{{ credentials_file }}"
        project_id: "{{ project_id }}"
        metadata: '{ "startup-script" : "apt-get update" }'
      register: gce

    - name: Save host data
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: gce_instances_ips
      with_items: "{{ gce.instance_data }}"

    - name: Wait for SSH for instances
      wait_for:
        delay: 1
        host: "{{ item.public_ip }}"
        port: 22
        state: started
        timeout: 30
      with_items: "{{ gce.instance_data }}"

    - name: Configure Hosts
      hosts: gce_instances_ips
      become: yes
      become_method: sudo
      roles:
        - lacchain-validator-node
      tags:
        - config
