---
- name: get packages and verify if libsodium is already installed
  shell: dpkg --get-selections | grep -w install |grep libsodium | awk '{print $1}'
  register: list_packages
  when: ansible_distribution |lower == 'ubuntu'

- name: Copy deb packages  of libsodium on Ubuntu equal to 16.04
  copy:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "/tmp/{{ item }}"
  with_items:
    -  "libsodium18_1.0.8-5_amd64.deb"
    -  "libsodium-dev_1.0.8-5_amd64.deb"
  when: ( ansible_distribution |lower == 'ubuntu' and ansible_distribution_version | truncate(2, True, '') > 16 )

- name: Install libsodium on Ubuntu > 16.04
  shell: "dpkg -i /tmp/{{ item }}"
  with_items:
    -  "libsodium18_1.0.8-5_amd64.deb"
    -  "libsodium-dev_1.0.8-5_amd64.deb"
  when: ( ansible_distribution |lower == 'ubuntu' and ansible_distribution_version | truncate(2, True, '') > 16 ) or
        ( list_packages.stdout.split() == '')

- debug:
    msg:
      - "Package {{ item }} is already installed"
  with_items:
      - "{{ list_packages.stdout.split() }}"
  when: ansible_distribution |lower == 'ubuntu'

- name: Install libsodium on Ubuntu equal to 16.04
  apt:
    name: "{{ item }}"
  with_items:
    - libleveldb-dev
    - libsodium-dev
  when: ( ansible_distribution |lower == 'ubuntu' and ansible_distribution_version | truncate(2, True, '') == 16 )

- name: set symbolic links to libsodium
  file:
    src: "/usr/lib/x86_64-linux-gnu/libsodium.so"
    dest: "/lib64/libsodium.so.18"
    state: link
  when: ( ansible_distribution |lower == 'ubuntu' )